spring.application.name=kart-user

# env path setup
spring.config.import=optional:file:../.env[.properties]

# Supabase connection setup
spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.username=${SUPABASE_DB_USER}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# flyway migration setup
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=kart_user
spring.flyway.default-schema=kart_user
spring.flyway.create-schemas=true

# server setup
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=kart_user
server.port=8081

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

# actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-components=always
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true